#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Team Play4Fun

# Short bio or description (displayed in the header)
description: Capture the flag competitors playing to kill time

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: p4f
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

members:
  jacobsoo:
    name: Jacob Soo
    display_name: jacobsoo
    gravatar:
    navatar:
    email: jacob[dot]soo[at]gmail[dot]com
    web: http://vxsecurity.sg/
    twitter: _jsoo_
    github: jacobsoo
    title: Couch Potato
    bio:
  klks84:
    name: klks84
    display_name: klks84
    gravatar:
    navatar: /images/avatar/klks84.png
    email: klks84[at]gmail[dot]com
    web:
    twitter: klks84
    github: klks
    title: Dude stealing your post-it passwords
    bio: Just some random dude playin ctf's
  CodeAndSec:
    display_name: CodeAndSec
    gravatar:
    navatar: https://pbs.twimg.com/profile_images/495394268781887489/iNZFUzH1_400x400.png
    email: info[at]codeandsec[dot]com
    web: https://www.codeandsec.com/
    twitter: CodeAndSec
    github: CodeAndSec
    title: 
    bio: Developer/PenTester/Programmer
  sine:
    display_name: sine
    gravatar:
    navatar: https://pbs.twimg.com/profile_images/1118700958/dna-double-helix-347.jpg
    email: 73696e65[at]gmail[dot]com
    web: https://keybase.io/sine
    twitter: 73696e65
    github: 73696e65
    title:
    bio: PenTester/Math Person
  xedi:
    display_name: xedi
    gravatar:
    navatar: https://pbs.twimg.com/profile_images/378800000530459313/8c0b65d0f7bbef8a9d72890107aaf113_400x400.jpeg
    email: xedi[at]idrizovic[dot]at
    web: 
    twitter: xedi25
    github: edix
    title:
    bio:
  jershmagersh :
    name: Joshua Reynolds
    display_name: jershmagersh  
    gravatar:
    navatar: https://pbs.twimg.com/profile_images/439195246379794433/SKvxQix9.png
    email: infosec4breakfast[at]gmail[dot]com
    web: http://pwnage.io
    twitter: jershmagersh
    github: jershmagersh
    title: Reverse Engineer 
    bio: "Canadian security enthusiast. Interests include: reversing, memory corruption, web application vulnerabilities, and coding."
  yohanes:
    display_name: yohanes
    gravatar: http://en.gravatar.com/yohanes
    email: yohanes[at]gmail[dot]com
    web: http://tinyhack.com
    twitter: yohanes
    github: yohanes
    title: 
    bio: Just another programmer
  stamparm:
    name: Miroslav Stampar
    display_name: stamparm
    gravatar: 
    navatar: https://pbs.twimg.com/profile_images/633392215348355072/yuRud64c.jpg
    email: miroslav[at]sqlmap[dot]org
    web: http://about.me/stamparm
    twitter: stamparm
    github: stamparm
    title: 
    bio: Trendy and likes ponies
